# IMAGE is an environment variable.
IMAGE_REPO_TAG=${IMAGE#*/}
IMAGE_REPO=${IMAGE_REPO_TAG%:*}
SANDBOX=$IMAGE_REPO

TEST_BASENAME=`basename $BATS_TEST_FILENAME`
TEST_SUBJECT=${TEST_BASENAME%.*}

CONTAINER_NAME=$SANDBOX-$TEST_SUBJECT
