# IMAGE is an environment variable.
IMAGE_REPO_TAG=${IMAGE#*/}
IMAGE_REPO=${IMAGE_REPO_TAG%:*}
TEST_SUITE=$IMAGE_REPO

TEST_BASENAME=`basename $BATS_TEST_FILENAME`
TEST_CASE=${TEST_BASENAME%.*}

CONTAINER_NAME=$TEST_SUITE-$TEST_CASE
