FILENAME=`basename $BATS_TEST_FILENAME`
IMAGE_REPO_TAG=${IMAGE#*/}
IMAGE_REPO=${IMAGE_REPO_TAG%:*}
IMAGE_TAG=${IMAGE_REPO_TAG#*:}
TEST_CASE=${FILENAME%.*}
TEST_SUITE=$IMAGE_REPO
CONTAINER_NAME=$TEST_SUITE-$TEST_CASE
